platform: linux

image_resource:
  type: docker-image
  source: {repository: mono}

inputs:
- name: ValueUncertaintyGame

outputs:
- name: ValueUncertaintyGameBuildResults

run:
  path: ./ValueUncertaintyGame/build.sh
